baseurl = "https://nickcouto.com"
languageCode = "pt-br"
Title = "nickcouto"
theme = "kiss"
# copyright = "&copy; <a href=\"https://github.com/ribice\">Emir Ribic</a> 2017"
disqusShortname = "nickcouto"
addThis = "ra-5b378311ceb84dca"
googleAnalytics = "UA-114106664-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "@nickcouto" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "nickcouto"
github = "nickcouto"
email = "nickcouto@gmail.com"
linkedin = "nickcouto"
# facebook = "ribice"
# instagram = ""
# codepen = ""

[params.matomoAnalytics]
siteID = 1
rootURL = "//nickcouto.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[params.sections_right]
"/about" = "about"

[params.sections_left]
"/" = "Design, UX, Product, 🤷🏻"
